### ISSUE TITLE
Fails to parse entity for `localhost`

### ISSUE THREAD

**Issue by mgburns** [patrickhulce/third-party-web#68]
## Steps to Reproduce

```node
const {getEntity} = require('third-party-web')
const entity = getEntity('http://localhost/example.html')

Error: Unable to find domain in "localhost"
    at getDomainFromOriginOrURL (/Users/mgburns/third-party-web-test/node_modules/third-party-web/lib/create-entity-finder-api.js:9:9)
    at getRootDomain (/Users/mgburns/third-party-web-test/node_modules/third-party-web/lib/create-entity-finder-api.js:13:18)
    at getEntityInDataset (/Users/mgburns/third-party-web-test/node_modules/third-party-web/lib/create-entity-finder-api.js:21:22)
```

I'm using this package by way of [Sitespeed.io](https://github.com/sitespeedio/sitespeed.io) and am trying to run performance tests against local URLs and this is causing it to fail.

**Comment by patrickhulce** [comment]
Thanks for filing @mgburns! :)
